language: elixir
services:
  - postgresql
addons:
  artifacts:
    working_dir: tmp
    paths:
      - ex_venture.tar.gz
    target_paths:
      - /${TRAVIS_COMMIT}/
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
elixir:
  - 1.8.0
otp_release:
  - 21.2
env:
  - MIX_ENV=test
cache:
  directories:
    - deps
    - _build/
install:
  - sudo -u postgres psql -p 5433 -c "create user exventure with superuser password 'password';"
  - cp .travis/test.exs config/test.exs
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix compile
  - mix do ecto.create, ecto.migrate
script:
  - mix credo
  - mix test
  - ./release.sh
