site_name: ExVenture
site_description: 'A MUD built with Elixir'
site_author: 'Eric Oestrich'
site_url: 'http://exventure.org'

repo_name: 'oestrich/ex_venture'
repo_url: 'https://github.com/oestrich/ex_venture'

copyright: 'Copyright &copy; 2017 Eric Oestrich'
google_analytics: ['UA-20355001-8', 'exventure.org']

theme:
  name: 'material'
  palette:
    primary: "Blue Grey"

pages:
  - Home: index.md
  - Setup: setup.md
  - Web Client: client.md
  - Game:
    - GMCP: game/gmcp.md
    - Help: game/help.md
    - Races: game/races.md
  - Admin:
    - Dashboard: admin/index.md
    - Classes: admin/classes.md
    - Config: admin/config.md
    - Effects: admin/effects.md
    - Help Topics: admin/help-topics.md
    - Insights: admin/insights.md
    - Items: admin/items.md
    - Races: admin/races.md
  - Metrics: metrics.md
