site_name: ExVenture
site_description: 'A MUD built with Elixir'
site_author: 'Eric Oestrich'
site_url: 'http://exventure.org'

repo_name: 'oestrich/ex_venture'
repo_url: 'https://github.com/oestrich/ex_venture'

copyright: 'Copyright &copy; 2017-2018 Eric Oestrich'
google_analytics: ['UA-20355001-8', 'exventure.org']

theme:
  name: 'material'
  logo:
    icon: layers
  palette:
    primary: "Blue Grey"

nav:
  - Home: index.md
  - Setup: setup.md
  - Contributing: contributing.md
  - Web Client: client.md
  - Deploying ExVenture: deploy.md
  - Game:
    - GMCP: game/gmcp.md
    - Help: game/help.md
    - Races: game/races.md
  - Admin:
    - Dashboard: admin/index.md
    - Classes: admin/classes.md
    - Config: admin/config.md
    - Effects: admin/effects.md
    - Gossip: admin/gossip.md
    - Help Topics: admin/help-topics.md
    - Insights: admin/insights.md
    - Items: admin/items.md
    - NPCs: admin/npcs.md
    - NPC Events: admin/events.md
    - Quests: admin/quests.md
    - Races: admin/races.md
    - Scripts: admin/scripts.md
    - Users: admin/users.md
    - Venture Markup Language: admin/vml.md
    - Zones: admin/zones.md
  - Metrics: metrics.md
  - Docker: docker.md
